### ISSUE TITLE
System.Exception: Running the docker.exe tag command failed

### ISSUE THREAD

**Issue by spacecat** [MicrosoftDocs/visualstudio-docs#1311]
2018-07-30 16:56:46
System.Exception: Running the docker.exe tag command failed.
   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.DockerTag(ProcessStartInfo startInfo, String serverUrlString)
   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.&lt;PostPublishAsync&gt;d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.&lt;RunPublishTaskAsync&gt;d__116.MoveNext()
===================

Got this error while running "Publish" image to ACR. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools#add-kubernetes-support-to-an-existing-project)
* Content Source: [docs/deployment/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-kubernetes-tools.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by spacecat** [comment]
Additional info:

I tested:

- run Visual Studio as Administrator
- Create a new ACR
- Use existing ACR
- Docker Hub

None of these work for me.

**Comment by olegburov** [comment]
I'm getting the same exception when publishing to Azure Container Registry or Web App for Containers using both VS `15.7.6` or `15.8.0 Preview-5` Community Edition:

![exception](https://user-images.githubusercontent.com/2487951/44011755-318f0664-9e6f-11e8-81d0-56b6ee9495e7.PNG)

**File tmpDF4C.tmp:**
```
8/12/2018 8:27:44 PM
System.Exception: Running the docker.exe tag command failed.
   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.DockerTag(ProcessStartInfo startInfo, String serverUrlString)
   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.<PostPublishAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__116.MoveNext()
===================
```
![docker](https://user-images.githubusercontent.com/2487951/44011778-639ee3ae-9e6f-11e8-9ac7-f2b9b2cf00bf.PNG)

**Comment by ghogen** [comment]
This doesn't seem to be a doc issue.  It's a product issue that was fixed recently.  I think it's OK to close this doc issue now.

**Comment by cklepeis** [comment]
Just experienced the same issue:
```
10/1/2018 4:04:36 PM
Microsoft.VisualStudio.Web.Azure.Publish.Docker.DockerCommandException: Running the docker.exe tag command failed.


   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.ThrowDockerCommandError(String dockerCommand)
   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.<DockerTagAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.Web.Azure.Publish.ContainerRegistryProfileVisual.<PostPublishAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__127.MoveNext()
===================
```

**Comment by guflorezm** [comment]
I got the same error when i try to publish my application into an azure container registry from my visual studio professional in windows 10

![image](https://user-images.githubusercontent.com/25715441/51767748-45dbb080-20ac-11e9-9ca1-8f2ad0e915df.png)

![grubbrr-published-error](https://user-images.githubusercontent.com/25715441/51767791-6a378d00-20ac-11e9-803b-3d41552fe02f.png)

![image](https://user-images.githubusercontent.com/25715441/51767847-8dfad300-20ac-11e9-820f-9840081e8fe6.png)

![image](https://user-images.githubusercontent.com/25715441/51767891-a539c080-20ac-11e9-9075-b827a80afa0a.png)

**Comment by jaycdave88** [comment]
I am running into the same issue with Visual Studio 2019 Community. I see this is marked as closed - is there a work around for this?

**Comment by BrainSlugs83** [comment]
I'm having this issue with VS 2019, .NET Core 3.1, and Docker 20.10.7.

Why is this marked as closed? -- It doesn't look like it's been fixed.

**Comment by ripvannwinkler** [comment]
@BrainSlugs83 I just recently started encountering this error as well. Seems like maybe a regression bug. Please maintainers, re-open this issue.

Log file:

`6/29/2021 7:17:19 PM
Microsoft.WebTools.Azure.Publish.Docker.DockerCommandException: Running the docker.exe tag command failed.

Current context "desktop-linux" is not found on the file system, please check your config file at C:\Users\chris\AppData\Local\Temp\a1080d75d02a45a299abc86fac658826\config.json
   at Microsoft.WebTools.Azure.Publish.Docker.DockerOperations.ThrowDockerCommandError(String dockerCommand)
   at Microsoft.WebTools.Azure.Publish.Docker.DockerOperations.<DockerTagAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WebTools.Azure.Publish.Docker.DockerPublish.<DockerPublishAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WebTools.Azure.Publish.ContainerRegistry.ManageContainerRegistry.<PushImageAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WebTools.Azure.Publish.PublishProviders.ContainerRegistryProfileVisual.<PostPublishAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Nexus.PublishProfilesServiceImpl.ServerProjectProfilesManager.<RunPublishTaskAsync>d__53.MoveNext()

===================
`

config.json referenced above:

`{
  "auths": {
    "*********.azurecr.io": {}
  },
  "credsStore": "desktop",
  "currentContext": "desktop-linux",
  "HttpHeaders": {
    "X-Meta-Source-Client": "vs/web/publish"
  }
}`

Relevant Visual Studio info:

Microsoft Visual Studio Professional 2019
Version 16.10.3
VisualStudio.16.Release/16.10.3+31424.327
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

C# Tools   3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Service Fabric Tools for Visual Studio   16.10
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

**Comment by ripvannwinkler** [comment]
FWIW, I was able to solve my problem yesterday by switching the docker context back to default (it was set to desktop-linux) using the command:

`docker context use default`

I'm not sure what caused it to switch to desktop-linux in the first place.

**Comment by WilliamAntonRohm** [comment]
@ripvannwinkler -- thank you for your followup.

cc @ghogen for awareness

**Comment by DanielChilcott** [comment]
Same issue here - was able to publish a container to Az Container registry yesterday. Can't get it to work today, not sure what's changed. 

![image](https://user-images.githubusercontent.com/6160988/124299307-31415380-db55-11eb-8889-00200033a7a6.png)

I've tried clearing my temp folder, uninstall, re-install of Docker Desktop, create new Az container registry, authenticating it with docker login, a new VS project, etc but still persists.

Content of .tmp file:

`2021/07/02 16:45:18
Microsoft.WebTools.Azure.Publish.Docker.DockerCommandException: Running the docker.exe tag command failed.

Current context "desktop-windows" is not found on the file system, please check your config file at C:\Users\Dan\AppData\Local\Temp\a6475e493a1a4d4e9b212eb3552fc61c\config.json
   at Microsoft.WebTools.Azure.Publish.Docker.DockerOperations.ThrowDockerCommandError(String dockerCommand)
   at Microsoft.WebTools.Azure.Publish.Docker.DockerOperations.<DockerTagAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WebTools.Azure.Publish.Docker.DockerPublish.<DockerPublishAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WebTools.Azure.Publish.ContainerRegistry.ManageContainerRegistry.<PushImageAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WebTools.Azure.Publish.PublishProviders.ContainerRegistryProfileVisual.<PostPublishAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__201.MoveNext()

===================
`

Content of JSON file

`{
  "auths": {
    "webapplication320210702161214.azurecr.io": {}
  },
  "credsStore": "desktop",
  "currentContext": "desktop-windows",
  "HttpHeaders": {
    "X-Meta-Source-Client": "vs/web/publish"
  }
}`

**Comment by SteffenMangold** [comment]
> FWIW, I was able to solve my problem yesterday by switching the docker context back to default (it was set to desktop-linux) using the command:
> 
> `docker context use default`
> 
> I'm not sure what caused it to switch to desktop-linux in the first place.

Thank! That worked for me. (restart VS after)

**Comment by Tailslide** [comment]
Got this after purging my AppData\Local\Temp directory. 
I think there is some necessary info persisted there which seems.. 'wrong'.
The command worked for me as well:

```docker context use default```

**Comment by icytin** [comment]
Got the same error after Docker was updated to 3.5.1. Thought it was something wrong with the install so I uninstalled and installed again, but same issue still when publish from Visual Studio 2019.

Tried the command suggested earlier in this thread, but that didn´t work in my case:
`docker context use default`

The file:
C:\Users\USERNAME\AppData\Local\Temp\0897cb94f6e94b5082c05b9680f41b27\config.json

Had context set to "desktop-linux", I guess that worked with the previous version. But after editing this file and changed context to "default" instead the publish was a success.

**Comment by ripvannwinkler** [comment]
Although the command `docker context use default` did solve the issue temporarily, it appears something in Visual Studio keeps resetting the docker context when opening or saving the solution (not sure which) and the problem resurfaces. This is getting really annoying.

**Comment by tesfayh** [comment]
This worked for me
https://developers.de/2018/01/01/error/
