### ISSUE TITLE
--noweb does not work for installer update

### ISSUE THREAD

**Issue by wbagdon** [MicrosoftDocs/visualstudio-docs#1592]
Running `vs_professional.exe --update --quiet --wait --noweb` to update the installer on a machine with no internet access results in the following output:

```
Beginning of the log. Start Time: 28/09/2018 21:13:10
VisualStudio Bootstrapper:28/09/2018 21:13:10: Current OptIn value is 1
VisualStudio Bootstrapper:28/09/2018 21:13:10: Commandline arguments = --update,--quiet,--wait,--noweb,--env,_SFX_CAB_EXE_PACKAGE:\\nasdub301-dm4\dtc\Software\Microsoft\VisualStudio\15\15.8.5\vs_professional.exe _SFX_CAB_EXE_ORIGINALWORKINGDIR:C:\WINDOWS
VisualStudio Bootstrapper:28/09/2018 21:13:10: The parameter after the command --update is an another command.
VisualStudio Bootstrapper:28/09/2018 21:13:10: Parent process name = vs_professional
VisualStudio Bootstrapper:28/09/2018 21:13:10: Parent process product version = 15.8.28010.2036
VisualStudio Bootstrapper:28/09/2018 21:13:10: CampaignId = 
VisualStudio Bootstrapper:28/09/2018 21:13:10: ResponseId not available in 'vs_setup_bootstrapper.config'. Trying to parse filename.
VisualStudio Bootstrapper:28/09/2018 21:13:10: loading config settings: -update --update --layout -offline --offline --locale --layout --originalworkingdir --installLayoutPath --env
VisualStudio Bootstrapper:28/09/2018 21:13:10: Client update requested: Not round trip.
VisualStudio Bootstrapper:28/09/2018 21:13:10: DownloadURL = https://aka.ms/vs/15/release/installer
VisualStudio Bootstrapper:28/09/2018 21:13:10: InstallLocation = C:\Program Files (x86)\Microsoft Visual Studio\Installer
VisualStudio Bootstrapper:28/09/2018 21:13:10: OfflineFilePath = 
VisualStudio Bootstrapper:28/09/2018 21:13:10: LayoutLocation = 
VisualStudio Bootstrapper:28/09/2018 21:13:10: ExecutableArguments = 
VisualStudio Bootstrapper:28/09/2018 21:13:10: OSVersion = Microsoft Windows NT 6.3.9600.0
VisualStudio Bootstrapper:28/09/2018 21:13:10: Starting to detect the existing VS and .Net...
VisualStudio Bootstrapper:28/09/2018 21:13:10: Finished detecting the existing VS and .Net
VisualStudio Bootstrapper:28/09/2018 21:13:10: Comparing client version '1.14.167.122' to autoSelfUpdateMinVersion '1.17.1298.831'
VisualStudio Bootstrapper:28/09/2018 21:13:10: Beginning file download. File = https://aka.ms/vs/15/release/installer.
VisualStudio Bootstrapper:28/09/2018 21:13:10: Download requested: https://aka.ms/vs/15/release/installer
VisualStudio Bootstrapper:28/09/2018 21:13:10: Attempting download 'https://aka.ms/vs/15/release/installer' using engine 'WebClient'
VisualStudio Bootstrapper:28/09/2018 21:13:10: WebClient error 'NameResolutionFailure' - proxy setting 'Default' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:13:10: WebClient error 'NameResolutionFailure' - proxy setting 'DefaultCredentialsOrNoAutoProxy' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:13:10: WebClient error 'NameResolutionFailure' - proxy setting 'NetworkCredentials' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:13:32: WebClient error 'ConnectFailure' - proxy setting 'DirectAccess' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:13:32: WebClient failed in 'https://aka.ms/vs/15/release/installer' with 'Unable to connect to the remote server' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:13:32: Download failed using WebClient engine. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 23.66.21.99:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.VisualStudio.Setup.Download.WebClientEngine.GetWebResponse(Uri uri, DownloadContext downloadContext, DownloadSummary& downloadSummary)
   at Microsoft.VisualStudio.Setup.Download.WebClientEngine.DownloadCore(Uri uri, Stream stream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:13:32: Sleeping 5000 milliseconds before retrying download.
VisualStudio Bootstrapper:28/09/2018 21:13:37: Attempting download 'https://aka.ms/vs/15/release/installer' using engine 'Bits'
VisualStudio Bootstrapper:28/09/2018 21:13:37: Download failed using Bits engine. System.Runtime.InteropServices.COMException (0x800704DD): The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
   at Microsoft.VisualStudio.Setup.Download.Bits.IBackgroundCopyJob.AddFile(String remoteUrl, String localName)
   at Microsoft.VisualStudio.Setup.Download.Bits.BitsJob.InitJob(String remoteUrl, String filePath, String cookie)
   at Microsoft.VisualStudio.Setup.Download.Bits.BitsJob.CreateJob(IServiceProvider serviceProvider, IBackgroundCopyManager backgroundCopyManager, Uri uri, String filePath, String cookie)
   at Microsoft.VisualStudio.Setup.Download.Bits.BitsEngine.DownloadCore(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:13:37: Sleeping 10000 milliseconds before retrying download.
VisualStudio Bootstrapper:28/09/2018 21:13:47: Attempting download 'https://aka.ms/vs/15/release/installer' using engine 'WinInet'
VisualStudio Bootstrapper:28/09/2018 21:13:47: Error in 'InternetOpenUrl' with '12007' - 'Unknown error 12007'.
VisualStudio Bootstrapper:28/09/2018 21:13:47: WinInet error 'UnknownError' Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007 - proxy setting 'DefaultCredentialsOrNoAutoProxy' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:13:47: Error in 'InternetOpenUrl' with '12007' - 'Unknown error 12007'.
VisualStudio Bootstrapper:28/09/2018 21:13:47: WinInet error 'UnknownError' Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007 - proxy setting 'DirectAccess' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:14:08: Error in 'InternetOpenUrl' with '12029' - 'Unknown error 12029'.
VisualStudio Bootstrapper:28/09/2018 21:14:08: WinInet failed 'https://aka.ms/vs/15/release/installer' with 'Function: InternetOpenUrl, HR: -2147012867, Message: Unknown error 12029'.
VisualStudio Bootstrapper:28/09/2018 21:14:08: Download failed using WinInet engine. Microsoft.VisualStudio.Setup.Download.WrappedWebException: Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007
   at Microsoft.VisualStudio.Setup.Download.WinInet.WinInetEngine.DownloadCore(Uri uri, Stream stream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:14:08: Caught Exception: Type = WrappedWebException, Message = Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007, StackTrace =    at Microsoft.VisualStudio.Setup.Download.WinInet.WinInetEngine.DownloadCore(Uri uri, Stream stream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:14:08: Failed to download. Error : Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007
VisualStudio Bootstrapper:28/09/2018 21:14:13: Beginning file download. File = https://aka.ms/vs/15/release/installer.
VisualStudio Bootstrapper:28/09/2018 21:14:13: Download requested: https://aka.ms/vs/15/release/installer
VisualStudio Bootstrapper:28/09/2018 21:14:13: Attempting download 'https://aka.ms/vs/15/release/installer' using engine 'WebClient'
VisualStudio Bootstrapper:28/09/2018 21:14:13: WebClient error 'NameResolutionFailure' - proxy setting 'Default' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:14:13: WebClient error 'NameResolutionFailure' - proxy setting 'DefaultCredentialsOrNoAutoProxy' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:14:13: WebClient error 'NameResolutionFailure' - proxy setting 'NetworkCredentials' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:14:34: WebClient error 'ConnectFailure' - proxy setting 'DirectAccess' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:14:34: WebClient failed in 'https://aka.ms/vs/15/release/installer' with 'Unable to connect to the remote server' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:14:34: Download failed using WebClient engine. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 23.66.21.99:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.VisualStudio.Setup.Download.WebClientEngine.GetWebResponse(Uri uri, DownloadContext downloadContext, DownloadSummary& downloadSummary)
   at Microsoft.VisualStudio.Setup.Download.WebClientEngine.DownloadCore(Uri uri, Stream stream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:14:34: Sleeping 5000 milliseconds before retrying download.
VisualStudio Bootstrapper:28/09/2018 21:14:39: Attempting download 'https://aka.ms/vs/15/release/installer' using engine 'Bits'
VisualStudio Bootstrapper:28/09/2018 21:14:39: Download failed using Bits engine. System.Runtime.InteropServices.COMException (0x800704DD): The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
   at Microsoft.VisualStudio.Setup.Download.Bits.IBackgroundCopyJob.AddFile(String remoteUrl, String localName)
   at Microsoft.VisualStudio.Setup.Download.Bits.BitsJob.InitJob(String remoteUrl, String filePath, String cookie)
   at Microsoft.VisualStudio.Setup.Download.Bits.BitsJob.CreateJob(IServiceProvider serviceProvider, IBackgroundCopyManager backgroundCopyManager, Uri uri, String filePath, String cookie)
   at Microsoft.VisualStudio.Setup.Download.Bits.BitsEngine.DownloadCore(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:14:39: Sleeping 10000 milliseconds before retrying download.
VisualStudio Bootstrapper:28/09/2018 21:14:49: Attempting download 'https://aka.ms/vs/15/release/installer' using engine 'WinInet'
VisualStudio Bootstrapper:28/09/2018 21:14:49: Error in 'InternetOpenUrl' with '12007' - 'Unknown error 12007'.
VisualStudio Bootstrapper:28/09/2018 21:14:49: WinInet error 'UnknownError' Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007 - proxy setting 'DefaultCredentialsOrNoAutoProxy' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:14:49: Error in 'InternetOpenUrl' with '12007' - 'Unknown error 12007'.
VisualStudio Bootstrapper:28/09/2018 21:14:49: WinInet error 'UnknownError' Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007 - proxy setting 'DirectAccess' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:15:10: Error in 'InternetOpenUrl' with '12029' - 'Unknown error 12029'.
VisualStudio Bootstrapper:28/09/2018 21:15:10: WinInet failed 'https://aka.ms/vs/15/release/installer' with 'Function: InternetOpenUrl, HR: -2147012867, Message: Unknown error 12029'.
VisualStudio Bootstrapper:28/09/2018 21:15:10: Download failed using WinInet engine. Microsoft.VisualStudio.Setup.Download.WrappedWebException: Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007
   at Microsoft.VisualStudio.Setup.Download.WinInet.WinInetEngine.DownloadCore(Uri uri, Stream stream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:15:10: Caught Exception: Type = WrappedWebException, Message = Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007, StackTrace =    at Microsoft.VisualStudio.Setup.Download.WinInet.WinInetEngine.DownloadCore(Uri uri, Stream stream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:15:10: Failed to download. Error : Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007
VisualStudio Bootstrapper:28/09/2018 21:15:15: Beginning file download. File = https://aka.ms/vs/15/release/installer.
VisualStudio Bootstrapper:28/09/2018 21:15:15: Download requested: https://aka.ms/vs/15/release/installer
VisualStudio Bootstrapper:28/09/2018 21:15:15: Attempting download 'https://aka.ms/vs/15/release/installer' using engine 'WebClient'
VisualStudio Bootstrapper:28/09/2018 21:15:15: WebClient error 'NameResolutionFailure' - proxy setting 'Default' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:15:15: WebClient error 'NameResolutionFailure' - proxy setting 'DefaultCredentialsOrNoAutoProxy' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:15:15: WebClient error 'NameResolutionFailure' - proxy setting 'NetworkCredentials' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:15:36: WebClient error 'ConnectFailure' - proxy setting 'DirectAccess' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:15:36: WebClient failed in 'https://aka.ms/vs/15/release/installer' with 'Unable to connect to the remote server' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:15:36: Download failed using WebClient engine. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 23.66.21.99:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.VisualStudio.Setup.Download.WebClientEngine.GetWebResponse(Uri uri, DownloadContext downloadContext, DownloadSummary& downloadSummary)
   at Microsoft.VisualStudio.Setup.Download.WebClientEngine.DownloadCore(Uri uri, Stream stream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:15:36: Sleeping 5000 milliseconds before retrying download.
VisualStudio Bootstrapper:28/09/2018 21:15:41: Attempting download 'https://aka.ms/vs/15/release/installer' using engine 'Bits'
VisualStudio Bootstrapper:28/09/2018 21:15:41: Download failed using Bits engine. System.Runtime.InteropServices.COMException (0x800704DD): The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
   at Microsoft.VisualStudio.Setup.Download.Bits.IBackgroundCopyJob.AddFile(String remoteUrl, String localName)
   at Microsoft.VisualStudio.Setup.Download.Bits.BitsJob.InitJob(String remoteUrl, String filePath, String cookie)
   at Microsoft.VisualStudio.Setup.Download.Bits.BitsJob.CreateJob(IServiceProvider serviceProvider, IBackgroundCopyManager backgroundCopyManager, Uri uri, String filePath, String cookie)
   at Microsoft.VisualStudio.Setup.Download.Bits.BitsEngine.DownloadCore(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:15:41: Sleeping 10000 milliseconds before retrying download.
VisualStudio Bootstrapper:28/09/2018 21:15:51: Attempting download 'https://aka.ms/vs/15/release/installer' using engine 'WinInet'
VisualStudio Bootstrapper:28/09/2018 21:15:51: Error in 'InternetOpenUrl' with '12007' - 'Unknown error 12007'.
VisualStudio Bootstrapper:28/09/2018 21:15:51: WinInet error 'UnknownError' Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007 - proxy setting 'DefaultCredentialsOrNoAutoProxy' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:15:51: Error in 'InternetOpenUrl' with '12007' - 'Unknown error 12007'.
VisualStudio Bootstrapper:28/09/2018 21:15:51: WinInet error 'UnknownError' Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007 - proxy setting 'DirectAccess' - 'https://aka.ms/vs/15/release/installer'.
VisualStudio Bootstrapper:28/09/2018 21:16:12: Error in 'InternetOpenUrl' with '12029' - 'Unknown error 12029'.
VisualStudio Bootstrapper:28/09/2018 21:16:12: WinInet failed 'https://aka.ms/vs/15/release/installer' with 'Function: InternetOpenUrl, HR: -2147012867, Message: Unknown error 12029'.
VisualStudio Bootstrapper:28/09/2018 21:16:12: Download failed using WinInet engine. Microsoft.VisualStudio.Setup.Download.WrappedWebException: Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007
   at Microsoft.VisualStudio.Setup.Download.WinInet.WinInetEngine.DownloadCore(Uri uri, Stream stream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:16:12: Caught Exception: Type = WrappedWebException, Message = Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007, StackTrace =    at Microsoft.VisualStudio.Setup.Download.WinInet.WinInetEngine.DownloadCore(Uri uri, Stream stream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.DownloadWithBitRate(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadEngineBase.Download(Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext)
   at Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
VisualStudio Bootstrapper:28/09/2018 21:16:12: Failed to download. Error : Function: InternetOpenUrl, HR: -2147012889, Message: Unknown error 12007
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: Sending Watson Bucket with:
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P1  = vs_setup_bootstrapper
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P2  = 1.17.1230.42073
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P3  = 
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P4  = ClientUpdate
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P5  = https://aka.ms/vs/15/release/installer
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P6  = n/a
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P7  = 0x80072ee7
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P8  = 
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P9  = 
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: P10 = 
VisualStudio Bootstrapper:28/09/2018 21:16:12: Watson: Including Log : C:\Users\taskdtcansible\AppData\Local\Temp\dd_bootstrapper_20180928211310.log
VisualStudio Bootstrapper:28/09/2018 21:16:12: Bootstrapper failed.
```

**Comment by wbagdon** [comment]
Also the RC 5003 is not included in the expected errors, it should be noted as above

**Comment by TerryGLee** [comment]
@wbagdon Thanks for your feedback; we're sorry to hear that you're having problems updating Visual Studio. If you can, we encourage you to file a bug directly though the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE. If you cannot access the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) tool, please know that we offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues.

**Comment by wbagdon** [comment]
I can't access that tool since the installer doesn't run

**Comment by TerryGLee** [comment]
@wbagdon Did you try the [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) option?  Also, here is some documentation that might be useful:

- [Create an offline installation of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
- [Create a network installation of Visual Studio 2017](Create a network installation of Visual Studio 2017)- [Update a network-based installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2017)

Another option too, is to use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by tinad123** [comment]
Thanks I'll try that

**Comment by wbagdon** [comment]
OK I'm unable to access these chat applications from my office.
I just wanted to report the issue and it seems there is not an easy way to do that.
