### ISSUE TITLE
Needs Visual Basic version

### ISSUE THREAD

**Issue by KNBD** [MicrosoftDocs/visualstudio-docs#1597]
I have worked through this example but I use Visual Basic.  I therefore had to translate it as I went.  From step 10 onwards things got more or less impossible.  Applying VB Event Handler definitions that had worked for me already elsewhere, I persevered.  However:
a) The only Constructor Function that I could find in my project that mentions 'InitializeComponent' explicitly says you should NOT edit it because it is created by the Designer (VSTO help does not mention Constructor Functions so that left me wondering if I was looking in the right place.
b)  Although the 'translation' to Visual Basic compiled without error it gives a weird error when the RaiseEvent for "Incremented" is called.  I made the entries in Public Sub Increment highly specific just to be sure but the Event simply is not raised.  Here is the Code (Lines 43-50) followed by the error.

    Public Sub Increment()
        currentValue += 1
        Label1.text = "Test text"
        Label1.Text = displayText & CStr(MyValue)
        Dim e As EventArgs
        e = New EventArgs
        RaiseEvent Incremented(Me, e)
    End Sub
THE ERROR AS COPIED 
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MyWinFormsControl
  StackTrace:
   at MyWinFormsControl.Counter.raise_Incremented(Object sender, EventArgs e) in C:\Users\neild\Documents\Visual Studio 2017\Projects\MyWinFormsControl\MyWinFormsControl\Counter.vb:line 16
   at MyWinFormsControl.Counter.Increment() in C:\Users\neild\Documents\Visual Studio 2017\Projects\MyWinFormsControl\MyWinFormsControl\Counter.vb:line 49
   at TestTextBoxTabC.Form1.Test_Click(Object sender, EventArgs e) in C:\Users\neild\Source\Repos\TestTextBoxTabC\TestTextBoxTabC\Form1.vb:line 3
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at TestTextBoxTabC.My.MyApplication.Main(String[] Args) in :line 81

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc4ffe3d-0607-7f67-54ae-0f4e08644dde
* Version Independent ID: a1d0d7ad-8341-fb52-77ac-76a870b6c69c
* Content: [Creating a Windows Forms Toolbox Control - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-windows-forms-toolbox-control?view=vs-2017)
* Content Source: [docs/extensibility/creating-a-windows-forms-toolbox-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-a-windows-forms-toolbox-control.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
