### ISSUE TITLE
Visual studio installed in container appears to partially break powershell or some part of package management

### ISSUE THREAD

**Issue by paylocity-sflanders** [MicrosoftDocs/visualstudio-docs#2396]
Was testing the functionality around doing builds in containers documented here

https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017

For the most part i thought everything was working but was noticing some strange warnings in some powershell regarding a file missing in the temp folder.  It only seems to happen after installing vs build tools.  I noticed breaking errors when i tried running a build that used Pester.  Below are more details

````
docker run --rm -it microsoft/dotnet-framework:4.7.1
C:\>powershell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\> Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -ErrorAction Stop | Out-Null
PS C:\> Install-Module Pester -RequiredVersion 4.6.0 -Force -SkipPublisherCheck -Scope AllUsers -ErrorAction Stop
PS C:\> Import-Module Pester -RequiredVersion 4.6.0
PS C:\> Pester\Invoke-Gherkin
Testing all features in 'C:\'
PS C:\>
````

As you can see everything loads without issue.  Now if you create a docker file like:

````
# escape=`

FROM microsoft/dotnet-framework:4.7.1

SHELL ["cmd", "/S", "/C"]
ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\temp\vs_buildtools.exe
RUN C:\temp\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --installPath C:\BuildTools `
    --add Microsoft.VisualStudio.Workload.AzureBuildTools `
    --add Microsoft.VisualStudio.Workload.DataBuildTools `
    --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools `
    --add Microsoft.VisualStudio.Workload.MSBuildTools `
    --add Microsoft.VisualStudio.Workload.NetCoreBuildTools `
    --add Microsoft.VisualStudio.Workload.NodeBuildTools `
    --add Microsoft.VisualStudio.Workload.WebBuildTools `
    --includeOptional --includeRecommended `
 || IF "%ERRORLEVEL%"=="3010" EXIT 0

CMD ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]
````

Build the docker image and then run a command like:

````
docker run --rm -it junk

PS C:\> Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -ErrorAction Stop | Out-Null
PS C:\> Install-Module Pester -RequiredVersion 4.6.0 -Force -SkipPublisherCheck -Scope AllUsers -ErrorAction Stop
PS C:\> Import-Module Pester -RequiredVersion 4.6.0
Add-Type : Could not find file 'C:\Users\ContainerAdministrator\AppData\Local\Temp\vis2a0vm\vis2a0vm.dll'.
+ & $SafeCommands['Add-Type'] -TypeDefinition @'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Could not find file 'C:\Users\ContainerAdministrator\AppData\Local\Temp\fnvgo3lr\fnvgo3lr.dll'.
At C:\Program Files\WindowsPowerShell\Modules\Pester\4.6.0\Pester.psm1:630 char:1
+ Add-Type -TypeDefinition @"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand
PS C:\> $Error.Exception
Could not find file 'C:\Users\ContainerAdministrator\AppData\Local\Temp\2avljy0j\2avljy0j.dll'.
Could not find file 'C:\Users\ContainerAdministrator\AppData\Local\Temp\bbndgny5\bbndgny5.dll'.
Could not find file 'C:\Users\ContainerAdministrator\AppData\Local\Temp\pk0vasom\pk0vasom.dll'.
Unable to find type [Microsoft.PowerShell.Commands.PowerShellGet.Telemetry].
PS C:\> $Error.Exception.StackTrace
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.PowerShell.Commands.AddTypeCommand.CompileAssemblyFromSource(List`1 generatedTypes)
   at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.PowerShell.Commands.AddTypeCommand.CompileAssemblyFromSource(List`1 generatedTypes)
   at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.PowerShell.Commands.AddTypeCommand.CompileAssemblyFromSource(List`1 generatedTypes)
   at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
PS C:\>
````

As you can see Pester completely errors out.   The errors always seem to be related to the temp folder but i can see the folder is there.   Any ideas whats causing this behavior or how to fix it?

I hit this issue on Windows Server 2016, 1607, 14393.2608  and Windows 10 Enterprise, 1709, 16299.904

**Comment by TerryGLee** [comment]
@paylocity-sflanders Thanks for your feedback. @heaths FYI.

**Comment by heaths** [comment]
Please file a product issue at https://developercommunity.visualstudio.com so it can get routed to an appropriate team for investigation. Include also the full stack trace of those errors (e.g. `$Error.Exception.StackTrace` should do it even for multiple errors).

**Comment by paylocity-sflanders** [comment]
https://developercommunity.visualstudio.com/content/problem/449766/visual-studio-installed-in-container-appears-to-pa.html

**Comment by TerryGLee** [comment]
@heaths @paylocity-sflanders Thanks; closing this GitHub Issue now that it's been filed with the Developer Community.
