### ISSUE TITLE
Create a Node.js and Express app in Visual Studio Error: Cannot read property 'item1' of undefined

### ISSUE THREAD

**Issue by MastaT1** [MicrosoftDocs/visualstudio-docs#3652]
Hi, 

  I was trying to run the example and copied and pasted the code to be sure there were no typo's. Here is what I have, can someone tell me why this is throwing an error?

index.js contains the following:

'use strict';
var express = require('express');
var router = express.Router();

var getData = function () {
    var data = {
        'item1': 'http://public-domain-photos.com/free-stock-photos-1/flowers/cactus-76.jpg',
        'item2': 'http://public-domain-photos.com/free-stock-photos-1/flowers/cactus-77.jpg',
        'item3': 'http://public-domain-photos.com/free-stock-photos-1/flowers/cactus-78.jpg'
    }
    return data;
}

router.get('/', function (req, res) {
    res.render('index', { title: 'Express', "data": getData() });
});

index.pug contains the following:

extends layout

block content
  h1= title
  p Welcome to #{title}
  script.
    var f1 = function() { document.getElementById('myImage').src='#{data.item1}' }
  script.
    var f2 = function() { document.getElementById('myImage').src='#{data.item2}' }
  script.
    var f3 = function() { document.getElementById('myImage').src='#{data.item3}' }

  button(onclick='f1()') One!
  button(onclick='f2()') Two!
  button(onclick='f3()') Three!
  p
  a: img(id='myImage' height='200' width='200' src='')

 I'm getting the following error and I don't know why:

TypeError: C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\views\index.pug:7
    5|   p Welcome to #{title}
    6|   script.
  > 7|     var f1 = function() { document.getElementById('myImage').src='#{data.item1}' }
    8|   script.
    9|     var f2 = function() { document.getElementById('myImage').src='#{data.item2}' }
    10|   script.

Cannot read property 'item1' of undefined
    at eval (eval at wrap (C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:33:62)
    at template (eval at wrap (C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:73:159)
    at Object.exports.renderFile (C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\node_modules\pug\lib\index.js:427:38)
    at Object.exports.renderFile (C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\node_modules\pug\lib\index.js:417:21)
    at View.exports.__express [as engine] (C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\node_modules\pug\lib\index.js:464:11)
    at View.render (C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\node_modules\express\lib\response.js:1012:7)
    at C:\Users\MastaT\source\repos\ExpressTestApp\ExpressTestApp\routes\index.js:7:9

**Comment by WilliamAntonRohm** [comment]
@MastaT1 Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
