### ISSUE TITLE
Unable to Start Snapshot Debugger - Attach Snapshot Debugger failed: System.Net.WebException: The remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by MegoCs** [MicrosoftDocs/visualstudio-docs#3723]
Unable to Start Snapshot Debugger - Attach Snapshot Debugger failed: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRequest.&lt;GetResponseInternal&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRequest.&lt;GetResponseInternal&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRequest.&lt;GetResponse&gt;d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRMCommunicationClient.&lt;&lt;GetAzureAppServiceAsync&gt;b__99_0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRMCommunicationClient.&lt;ExecuteWithRetryTokenRefresh&gt;d__101`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRMCommunicationClient.&lt;GetAzureAppServiceAsync&gt;d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRMCommunicationClient.&lt;InitializeSessionConfig&gt;d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProductionDebug.DebugSession.ProductionDebugSession.&lt;StartSessionAsync&gt;d__41.MoveNext()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0557fd8-48c5-bbee-04b9-27baeb8858e6
* Version Independent ID: 2b397dd4-cfd5-78a8-9256-d1fb981b30bf
* Content: [Troubleshooting snapshot debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-live-azure-apps-troubleshooting?view=vs-2019#feedback)
* Content Source: [docs/debugger/debug-live-azure-apps-troubleshooting.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-live-azure-apps-troubleshooting.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@MegoCs Thanks for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
