### ISSUE TITLE
Development certificate does not work on latest Windows+VS+Excel

### ISSUE THREAD

**Issue by rgwood** [MicrosoftDocs/visualstudio-docs#4926]
Hi, this walkthrough fails for me at the "Test the project" step. The Excel addin fails to load because "the certificate used to sign the deployment manifest for ExcelAddin1 or its location is not trusted."

## Detailed error message (with account name removed)

```
Name: ExcelAddIn1 - ExcelAddIn1
From: file:///C:/Users/MYACCOUNTNAME/source/repos/ExcelAddIn1/ExcelAddIn1/bin/Debug/ExcelAddIn1.vsto

************** Exception Text **************
System.Security.SecurityException: Customized functionality in this application will not work because the certificate used to sign the deployment manifest for ExcelAddIn1 or its location is not trusted. Contact your administrator for further assistance.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.ProcessSHA2Manifest(ActivationContext context, DeploymentSignatureInformation signatureInformation, PermissionSet permissionsRequested, Uri manifest, ManifestSignatureInformationCollection signatures, AddInInstallationStatus installState, TrustStatus sha256TrustStatus, X509Certificate2 sha256PublisherCert)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
The Zone of the assembly that failed was:
MyComputer
```

## Software versions

Windows 10 1909
Visual Studio Community 2019, 16.4.6
Office Developer Tools for Visual Studio   16.0.29419.101
Excel for Office 365 MSO 16.0.12527.20242

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926f7f34-3f79-cfe2-c9ea-2d36bcdbafae
* Version Independent ID: 7ac3f98c-c147-3378-a2c8-7bd2944a2acd
* Content: [Walkthrough: Create your first VSTO Add-in for Excel - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel?view=vs-2019#feedback)
* Content Source: [docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@rgwood -- Reilly, thank you for your feedback.  You may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@John-Hart -- please look into this issue.

**Comment by gregorvilkner** [comment]
I have the same issue. This has been a nightmare for years! I spent more time troubleshooting trust issues with my own plugins then to create them.
