### ISSUE TITLE
Visual Studio 2017, deploy and debug remotely

### ISSUE THREAD

**Issue by comarius** [MicrosoftDocs/visualstudio-docs#502]
Remote Machine:          Windows 10, factory installed. Plus Remote debugger 2017 for visual studio 2017
Development Machine: VS Professional 2017 and a presentation framework simple project.

1. Project runs and and can be debugged locally.
2. Project deployed remotely from VS, is ok, but after every run/debug remote has to rebooted/ or log-off/on due above issue I post it.
3. Project crashes on remote with:
```

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=The method or operation is not implemented.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at QuanimusPro.Views.StartWindow.InitializeComponent() in C:\Users\<path to project>\Views\StartWindow.xaml:line 1

Inner Exception 1:
NotImplementedException: The method or operation is not implemented.

```

**Comment by gewarren** [comment]
@comarius These issues are designed to address documentation defects, not product questions. We can try to help, but a better place to post product feedback is at https://developercommunity.visualstudio.com/.

**Comment by gewarren** [comment]
@Mikejo5000 can you forward this info to the product team?

**Comment by Mikejo5000** [comment]
Yes, waiting for a response.

**Comment by andysterland** [comment]
You can report issues with the remote debugger over on the Visual Studio developer community: https://developercommunity.visualstudio.com/topics/ide.html?sort=active 
When you do please add some more information. As in, is the remote debugger attached every time you launch? What happens if you just launch the exe multiple times remotely. If you have the app and can share it so we can try to reproduce the issue etc.
