### ISSUE TITLE
Unable to run the command node_modules\.bin\webpack app.tsx --config webpack-config.js 

### ISSUE THREAD

**Issue by jayanthimurugesan** [MicrosoftDocs/visualstudio-docs#5269]
C:\Users\LENOVO\source\repos\NodejsWebAppBlank&gt;node_modules\.bin\webpack app.tsx --config webpack-config.js
C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: Cannot find module 'C:\Users\LENOVO\source\repos\NodejsWebAppBlank\webpack-config.js'
Require stack:
- C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\utils\convert-argv.js
- C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\cli.js
- C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (&lt;anonymous&gt;)
    at module.exports (C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\yargs\yargs.js:567:18)
    at C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.&lt;anonymous&gt; (C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.&lt;anonymous&gt; (C:\Users\LENOVO\source\repos\NodejsWebAppBlank\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\LENOVO\\source\\repos\\NodejsWebAppBlank\\node_modules\\webpack-cli\\bin\\utils\\convert-argv.js',
    'C:\\Users\\LENOVO\\source\\repos\\NodejsWebAppBlank\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\Users\\LENOVO\\source\\repos\\NodejsWebAppBlank\\node_modules\\webpack\\bin\\webpack.js'
  ]
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019#feedback)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@jayanthimurugesan -- thank you for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by Mikejo5000** [comment]
@jayanthimurugesan I would double-check that the npm packages, webpack and the webpack-cli are installed as described previously in the article, and that you have added webpack-config.js to the project root directory as described in the article.
